version: '3.5'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: altara_php
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: altara_webserver
    tty: true
    ports:
      - "7070:80"
      - "7071:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: altara_db
    tty: true
    ports:
      - "7072:3306"
    environment:
      MYSQL_DATABASE: altara
      MYSQL_ROOT_PASSWORD: password
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  #adminer
  adminer:
    image: adminer
    container_name: Al_Admin
    ports:
      - 7073:8080
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    name: altara
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
