<?php

return [
    'CustomerID',
    'Branch Code',
    'Surname',
    'First name',
    'Middle name',
    'Date of Birth',
    'National Identity Number',
    'Drivers License No',
    'BVN No',
    'Passport No',
    'Gender',
    'Nationality',
    'Marital Status',
    'Mobile number',
    'Primary Address Line 1',
    'Primary Address Line 2',
    'Primary city/LGA',
    'Primary State',
    'Primary Country',
    'Employment Status',
    'Occupation',
    'Business Category',
    'Business Sector',
    'Borrower Type',
    'Other ID',
    'Tax ID',
    'Picture File Path',
    'E-mail address',
    'Employer Name',
    'Employer Address Line 1',
    'Employer Address Line 2',
    'Employer City',
    'Employer State',
    'Employer Country',
    'Title',
    'Place of Birth',
    'Work phone',
    'Home phone',
    'Secondary Address Line 1',
    'Secondary Address Line 2',
    'Secondary Address City/LGA',
    'Secondary Address State',
    'Secondary Address Country',
    'Spouse\'s Surname',
    'Spouse\'s First name',
    'Spouse\'s Middle name ',
];
